### ISSUE TITLE
Merge into `language-crystal-actual`

### ISSUE THREAD

**Issue by keplersj** [tbpgr/atom_crystal_snippet_tb#1]
You've got some awesome snippets in here. I think it would be awesome if you pull requested some of these into `language-crystal-actual`. I'm willing to give you organization access to the repo if you are interested.

**Comment by tbpgr** [comment]
Thank you.
(I am sorry that I am not good with English)

> I think it would be awesome if you pull requested some of these into language-crystal-actual. 
> I'm willing to give you organization access to the repo if you are interested.

Yes, I want to access the organization.

## Suggestion
- [x] 1. (keplersj) invite tbpgr to the organization.
- [x] 2. (tbpgr) create pull request to `language-crystal-actual` .all snippet.
- [x] 3. (keplersj) choose snippet.
- [x] 4. (keplersj or tbpgr) delete unnecessary snippet.
- [x] 5. (keplersj) merge pull request + bump up version.
- [x] 6. (tbpgr) deprecate `atom_crystal_snippet_tb` . add link to `language-crystal-actual` in README.

**Comment by keplersj** [comment]
Welcome to atom-crystal! You should have received an invitation in your inbox, alternatively you can accept the invitation by visiting the [organization's GitHub page](https://github.com/atom-crystal).

**Comment by tbpgr** [comment]
@keplersj thanks! :smile: :crystal_ball:

**Comment by keplersj** [comment]
I just played around with the newly patched grammar and it works well! Thanks for writing the snippets and pull requesting them. If you have any more snippets you think would be useful, please, feel free to commit them to the grammar.

**Comment by tbpgr** [comment]
@keplersj thanks!

![LGTM](http://cbchintaicom-singlehack.s3-website-ap-northeast-1.amazonaws.com/content/uploads/2015/01/Red-kitten.jpg) 

> If you have any more snippets you think would be useful, please, feel free to commit them to the grammar.

ok :smile:

**Comment by tbpgr** [comment]
DEPRECATED
https://github.com/tbpgr/atom_crystal_snippet_tb

![_072916_060302_am](https://cloud.githubusercontent.com/assets/4787509/17229363/1e4d4fc4-5552-11e6-89ee-6a12ca137892.jpg)

https://atom.io/packages/atom_crystal_snippet_tb

![_072916_060400_am](https://cloud.githubusercontent.com/assets/4787509/17229391/40c263a0-5552-11e6-81d0-c8544c4ccefe.jpg)
