### ISSUE TITLE
Change repo's 'crystallang' topic to 'crystal'

### ISSUE THREAD

**Issue by matiasgarciaisaia** [tbpgr/atom_crystal_snippet_tb#2]
The Crystal community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

To avoid fragmentation in the community, please change the `crystallang` topic, that only has ~12 repositories at the moment, to `crystal`.

Any contributor can change it from the repo's homepage.

See crystal-lang/crystal#4241 for more context.

Thank you very much :)

**Comment by tbpgr** [comment]
Ok. I fix it.

![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png) 

![tbpgr_atom_crystal_snippet_tb](https://cloud.githubusercontent.com/assets/4787509/24716836/43d437f6-1a6b-11e7-8c62-3c058795d9c6.png)
